variables:
  # Azure authentication
  ARM_CLIENT_ID: ${ARM_CLIENT_ID}
  ARM_CLIENT_SECRET: ${ARM_CLIENT_SECRET}
  ARM_SUBSCRIPTION_ID: ${ARM_SUBSCRIPTION_ID}
  ARM_TENANT_ID: ${ARM_TENANT_ID}
  
  # Terraform settings
  TF_ROOT: ${CI_PROJECT_DIR}/conditional-access-policies

stages:
  - init
  - validate
  - plan
  - apply

init:
  image: hashicorp/terraform:1.5.7
  stage: init
  script:
    - cd ${TF_ROOT}
    - terraform version
    - terraform init
  artifacts:
    paths:
      - ${TF_ROOT}/.terraform
    expire_in: 1 hour

validate:
  image: hashicorp/terraform:1.5.7
  stage: validate
  script:
    - cd ${TF_ROOT}
    - terraform version
    - terraform validate
    - terraform fmt -check -recursive
  dependencies:
    - init

plan:
  image: hashicorp/terraform:1.5.7
  stage: plan
  script:
    - cd ${TF_ROOT}
    - terraform version
    - terraform plan -out=tfplan
  artifacts:
    paths:
      - ${TF_ROOT}/tfplan
    expire_in: 1 week
  dependencies:
    - init

apply:
  image: hashicorp/terraform:1.5.7
  stage: apply
  script:
    - cd ${TF_ROOT}
    - terraform version
    - terraform apply -auto-approve tfplan
  dependencies:
    - plan
    - init
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"
      when: manual