variables:
  # Azure authentication
  ARM_CLIENT_ID: ${ARM_CLIENT_ID}
  ARM_CLIENT_SECRET: ${ARM_CLIENT_SECRET}
  ARM_SUBSCRIPTION_ID: ${ARM_SUBSCRIPTION_ID}
  ARM_TENANT_ID: ${ARM_TENANT_ID}
  
  # Terraform settings
  TF_ROOT: ${CI_PROJECT_DIR}/conditional-access-policies
  # Variables file path
  TF_VAR_FILE: ${CI_PROJECT_DIR}/conditional-access-policies/terraform.tfvars

stages:
  - validate
  - plan
  - apply

default:
  image: hashicorp/terraform:1.5.7
  before_script:
    - mkdir -p ${TF_ROOT}
    - cd ${TF_ROOT}
    - terraform --version

validate:
  stage: validate
  script:
    - terraform init
    - terraform validate
    - terraform fmt -check -recursive

plan:
  stage: plan
  script:
    - terraform init
    - terraform plan -var-file="${TF_VAR_FILE}" -out=tfplan
  artifacts:
    paths:
      - ${TF_ROOT}/tfplan
    expire_in: 1 week

apply:
  stage: apply
  script:
    - terraform init
    - terraform apply -auto-approve tfplan
  dependencies:
    - plan
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"
      when: manual